### PR TITLE
update app listener port with .env variable

### PR DESCRIPTION
**Pull request by IsaacJrTypes**
This PR contains a quality of life update! Now you can set the API address from your .env file.

How to test:
- Use the .env.sample to help set up your .env file. Once set,  run backend and use postman or frontend (next.js) to make API calls to the server
- Make sure localhost port number matches with backend port number if using frontend

### CODE REVIEW

**Review by bcko — APPROVED** [review]
great job

**Comment by ParysUnangst** [comment]
Thank you for changing this Issac!

**Comment by cshimm** [comment]
This is a much-needed feature! 
I was thinking a default value of 3000 might make sense in the case where process.env.PORT is null or undefined. something like  `app.listen(process.env.PORT || 3000);`? Just a thought. nice job though!

**Review by cshimm — APPROVED** [review]
Looks great!

**Comment by Alzavio** [comment]
Looks great!

**Review by Alzavio — APPROVED** [review]
Looks great! This might be an unrelated discussion, but I wonder if we could list the env's needed for the project on .env.sample or somewhere else. I'm new to the project, so it took me a sec to figure that out

**Comment by bcko** [comment]
> Looks great! This might be an unrelated discussion, but I wonder if we could list the env's needed for the project on .env.sample or somewhere else. I'm new to the project, so it took me a sec to figure that out

@Alzavio great idea.

**Review by bcko — APPROVED** [review]

**Pull request merged**
