### PR TITLE
nsc-events-nestjs-3-36-update-yaml-file

### LINKED ISSUE #36: Test CI/CD systems: PR Update Test
Test to see if the new commit can retrigger CI.

### PR DESCRIPTION
**Pull request by TroyFPV48**
resolves #36 
Test if CI gets retriggered.

### CODE REVIEW

**Comment by tinpham5614** [comment]
Remove the new lines in lines 16 and 17 to resolve the issue in the main.ts

**Comment by TroyFPV48** [comment]
> Remove new lines in lines 16 and 17 to resolve the issue in the main.ts

I removed but there's still error.

**Comment by tinpham5614** [comment]
Got it fixed

**Review by taylorpapke — APPROVED** [review]
Looks good!

**Review by bcko — APPROVED** [review]

**Pull request merged**
