### PR TITLE
nsc-events-nestjs-8-129-auto-archive-past-events

### PR DESCRIPTION
**Pull request by Ali-7s**
Satisfies #129 
* Implements functionality to auto archive past events in the backend

https://github.com/SeattleColleges/nsc-events-nestjs/assets/22021615/6db5b2f5-7993-49e9-a1f4-9d23659732c9

### CODE REVIEW

**Review by heosman — APPROVED** [review]
It's working great. My events on the frontend that were expired were not on the Home page and the events that I edited to be before the current date and time were also archived. It seems one of the tests is now outdated because of your changes, you'll need to update the test before this is merged.

**Review by JesseCaddell — APPROVED** [review]
Working well on my end! Made an event with a date that has passed, and it was auto added to the archived events page.
image

**Review by bennettsf — COMMENTED** [review]
Works great but might I suggest making it archive the event at the end of the day that it happens? That way the event can still be looked at on the current day it's scheduled for.

**Comment by heosman** [comment]
@bennettsf I agree, that would be better. Or making the events archive as soon it hits the event's end time, perhaps? @Ali-7s Could we do this?

**Comment by Ali-7s** [comment]
> @bennettsf I agree, that would be better. Or making the events archive as soon it hits the event's end time, perhaps? @Ali-7s Could we do this?

Yeah, I just updated the code to implement it

**Comment by MaddasaHatter** [comment]
I'm late to the party but this looks great and functions as expected on my end when I create events with past due dates. Good job!

**Comment by heosman** [comment]
> > @bennettsf I agree, that would be better. Or making the events archive as soon it hits the event's end time, perhaps? @Ali-7s Could we do this?
> 
> Yeah, I just updated the code to implement it

@Ali-7s The events are no longer archiving with expired events or when I create events with past due dates or events that have started.

image

**Comment by Ali-7s** [comment]
> > > @bennettsf I agree, that would be better. Or making the events archive as soon it hits the event's end time, perhaps? @Ali-7s Could we do this?
> > 
> > 
> > Yeah, I just updated the code to implement it
> 
> @Ali-7s The events are no longer archiving with expired events or when I create events with past due dates or events that have started.
> 
> image

Sorry about that, it should work now based on date and event end time

https://github.com/SeattleColleges/nsc-events-nestjs/assets/22021615/e01a558e-756f-45c5-aa85-23638cdfaaa6

**Comment by heosman** [comment]
> > > > @bennettsf I agree, that would be better. Or making the events archive as soon it hits the event's end time, perhaps? @Ali-7s Could we do this?
> > > 
> > > 
> > > Yeah, I just updated the code to implement it
> > 
> > 
> > @Ali-7s The events are no longer archiving with expired events or when I create events with past due dates or events that have started.
> > image
> 
> Sorry about that, it should work now based on date and event end time
> 
>  Screen.Recording.2024-06-11.at.8.mp4

@Ali-7s It's working, but it seems I am only able to get an event to auto archive if the event is created using the Create Event page. Strangely, events created using Postman do not auto archive on my end.

**Comment by Ali-7s** [comment]
> > > > > @bennettsf I agree, that would be better. Or making the events archive as soon it hits the event's end time, perhaps? @Ali-7s Could we do this?
> > > > 
> > > > 
> > > > Yeah, I just updated the code to implement it
> > > 
> > > 
> > > @Ali-7s The events are no longer archiving with expired events or when I create events with past due dates or events that have started.
> > > image
> > 
> > 
> > Sorry about that, it should work now based on date and event end time
> > Screen.Recording.2024-06-11.at.8.mp4
> 
> @Ali-7s It's working, but it seems I am only able to get an event to auto archive if the event is created using the Create Event page. Strangely, events created using Postman do not auto archive on my end. Did you create your events using the Create Event page or Postman?

I created mine using the create event page

**Pull request merged**
