### PR TITLE
Feature 28 create user controller and service

### PR DESCRIPTION
**Pull request by Exochos**
nsc-events-nestjs_sprint2_Feature 28 create user controller and service

draft here. Postman works.

http://localhost:3000/api/auth/adminadduser
http://localhost:3000/api/auth/admindelete
http://localhost:3000/api/auth/adminupdateuser

### CODE REVIEW

**Comment by taylorpapke** [comment]
@theGaryLarson I'm noticing that on PR's where another push is made, CI is running Continuous-Integration / build-and-test and not completing. @Exochos I'm pretty sure if this PR is closed and reopened, it will run CI (on pull-request) / Continuous-Integration / build-and-test (pull_request) and complete. Perhaps something to look into more.

**Comment by theGaryLarson** [comment]
> @theGaryLarson I'm noticing that on PR's where another push is made, CI is running Continuous-Integration / build-and-test and not completing. @Exochos I'm pretty sure if this PR is closed and reopened, it will run CI (on pull-request) / Continuous-Integration / build-and-test (pull_request) and complete. Perhaps something to look into more.

@taylorpapke Thanks for pointing this out. I noticed that opening and reopening doesn't retrigger the CI but a push does. Something I didn't really notice when it was my branches I was pushing too. I will have to tweak CI to trigger when PR is opened so we can trigger it on other's PRs.

**Comment by Exochos** [comment]
Lot to unpack here:
I started off by refactoring the /auth/schema/userAuthSchema into --> userAuth.model.
This was done so I could use the User routes as there was a naming conflict.
Next we un-commented all of the /user routes and and got them all running, along with refactoring some of the code to user the create-user.dto instead of structs which they had been using. Also added a couple of routes. Additionally I added a password field to the create-user.dto to allow the admin to add a password when creating a new user (before it would create a user but without a password which means they could never login.) I have added my postman tests below along with their corresponding local MongoDB database for comparison. 


Adding a user.
adduserPostman

Updating a user.
updateUserPostman

Deleting a user.
deleteUserPostman

**Review by theGaryLarson — APPROVED** [review]
Looks good. I fixed the CodeFactor errors. there were three 2 were just minor styling adjustments and 1 was when renaming UserSchema to UserAuthSchema the import wasn't adjusted in the auth>schema or auth>module.

Also, I made some minor changes to the endpoints to follow the standards. pluralized user. Now users. and added find word to findById path e.g. `users/find/:id`

**Pull request merged**
