### PR TITLE
nsc-events-nestjs_5_106_user_events_API_endpoint

### LINKED ISSUE #106: View My Events Page: Create API endpoint that requests all events created by a specific user (by user ID)
Related: https://github.com/SeattleColleges/nsc-events-nextjs/issues/251

getActivitiesByUserId API endpoint

I would like to create an API endpoint that will access a specific user's created events from the database. This will be helpful for the related issue above, as it will allow us to display events on the 'View My Events' page that were created by the currently logged-in user.

### PR DESCRIPTION
**Pull request by bennettsf**
Resolves #106 
Related: [#251-nextjs-repo](https://github.com/SeattleColleges/nsc-events-nextjs/issues/251)

API endpoint that will access a specific user's created events from the database. Will be used for the View My Events admin/creator page to display the currently logged-in user's events they have created.

For testing (this assumes you have your database setup already):

1. Change to the development branch **feature-106-user-events-API-endpoint-01**. 
2. Start the backend nsc-events-nestjs server! `npm run start:dev`
3. After creating a few events on multiple users (through API calls or through the local nextjs UI), go to your MongoDB compass and grab the User ID from any of the Events you created. The User ID is found in the `createdByUser` property.
4. Paste that User ID in the Postman app as a GET request. (Append it to the end of `http://localhost:3000/api/events/user/`)
5. If you have any trouble setting this up, don't hesitate to reach out to me!

https://github.com/SeattleColleges/nsc-events-nestjs/assets/33855430/9831b367-ce00-4cf5-a5bb-e494ec39f806

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Works for me:
Screenshot 2024-04-22 at 2 20 34 PM
Screenshot 2024-04-22 at 2 21 09 PM

Please fix the code factor issues and update this PR when you get a chance.

**Comment by bennettsf** [comment]
> Please fix the CodeFactor issues and update this PR when you get a chance.

Sorry but I might need a hand here @taylorpapke... I have no idea what it's trying to tell me to fix. The first issue was already fixed is my last push and the second issue seems to be identical to the fix it's telling me to do. Am I just not seeing it correctly? I compared it with some similar functions and copied the exact styling.

**Review by brinkbrink — COMMENTED** [review]
Screenshot 2024-04-23 at 8 21 01 PM

Somebody correct me if I'm wrong but I'm pretty sure the arrow is to represent a new line and the dots are spaces. Hope that helps. 

Having a [prettier](https://prettier.io/docs/en/editors.html) extension installed in your IDE will save you from these headaches in the future.

**Review by brinkbrink — APPROVED** [review]

**Review by heosman — APPROVED** [review]
It's working for me when I test the API endpoint on Postman, good work!

image

**Comment by MaddasaHatter** [comment]
It's looking good. It was really helpful to see the progress being made in this thread and to see how the issue was ultimately resolved. Good job.

**Pull request merged**
