### PR TITLE
nsc-events-nestjs-06-116_events_not_in_ascending_order

### LINKED ISSUE #116: BUG: Events not in ascending order
Events retrieved from getAllEvents are not in ascending order I.E. events that occur sooner should appear above events that occur later.
image

### PR DESCRIPTION
**Pull request by cshimm**
Resolves #116 

This change will ensure the events returned from getAllEvents will be in ascending order by event date. 
image

### CODE REVIEW

**Review by bennettsf — COMMENTED** [review]
I think this works well. We might need to implement this for the View My Events and Archived Events pages. I'm wondering if it might be better to make a utility function in the frontend code to do the sorting after a GET request is made, but I can't really think of a reason why we would want the Events to be requested out of order in the first place.

**Comment by nwm516** [comment]
Great work! I created the top two events most recently, first with Old Timey and next, the 1990's event. Every event ended up going where they needed to. LGTM!

Events in Order

**Review by nwm516 — APPROVED** [review]
LGTM!

**Review by heosman — APPROVED** [review]
Working as expected!

image

**Review by bennettsf — APPROVED** [review]

**Comment by MuhammadNSC** [comment]
This works as explained. The test case named getAllActivities and additional sort them in the ascending order. Looks good.

**Pull request merged**
