### PR TITLE
nsc-events-nestjs_3_51_update-delete-function-id-parameter

### LINKED ISSUE #51: Delete Events from Database: Update delete function to take objectId as id parameter
As an admin, I will want to update the delete function to take in the objectId as the id parameter.

Relates to [User Story #54](https://github.com/SeattleColleges/nsc-events-android/issues/54) from [NSC-Events-Android](https://github.com/SeattleColleges/nsc-events-android)

### PR DESCRIPTION
**Pull request by intisarosman1**
Resolves #51 

As a developer, I updated the delete function to take in the objectId as the id parameter so that the frontend could make the call to the backend to fulfill the soft deletion request.

Relates to [User Story #54](https://github.com/SeattleColleges/nsc-events-android/issues/54) from [NSC-Events-Android](https://github.com/SeattleColleges/nsc-events-android)

### CODE REVIEW

**Comment by Exochos** [comment]
Looks like the delete request is correct and would work if I had the backend working and on the correct port.
pullrequest

**Comment by Exochos** [comment]
pullrequest
Looks like everything is working correctly, but I don't have the backend hooked up so I can't speak to that.

**Review by Exochos — COMMENTED** [review]
image
Looks like everything is correct.

**Comment by taylorpapke** [comment]
@Robel-003 @tinpham5614 @CourtneyHoppus I would suspect that this is similar to what we are experiencing on Belindas Closet https://github.com/SeattleColleges/belindas-closet-nestjs/pull/64 in terms of missing a unit test for the delete function according to:
Screenshot 2023-11-29 at 2 33 22 PM
Can we just have one of you create a separate issue and PR that will address/fix this PR so it can pass CI?

This is also addressed in a comment within https://github.com/SeattleColleges/belindas-closet-nestjs/pull/68

**Review by CourtneyHoppus — CHANGES_REQUESTED** [review]
I don't understand what you are trying to do here.
In the PR you state you "updated the delete function to take in the objectId as the id parameter" yet the code changes here are adding the `isHidden` property to the mock data and the service unit test for the `deleteActivityById` function and changing a period to an exclamation point in the service function `getActivityById`.
Also there is no information on how to test these changes and what this update accomplished.

**Comment by CourtneyHoppus** [comment]
@taylorpapke this is failing the Service unit test for the `deleteActivityById` but I don't think it has anything to do with what is going on with Belinda's. If you see my comment above, I suspect that the changes that are made here are causing the test to fail The NSC Events repo is set up that any unit tests in the .spec files are run and must pass to be able to merge. This PR is up to date with main, so the only thing that has changed is what is in this PR.

**Comment by intisarosman1** [comment]
This issue was originally to update the delete function to take in the objectId instead so that the frontend button could function properly, but I see that [PR #48](https://github.com/SeattleColleges/nsc-events-nestjs/pull/48) by @Robel-003 that was pulled today addressed this as well, so this PR is no longer necessary. I just tested his changes in main, and it works from the frontend so I will close this PR.
Sorry about the confusion.

**Pull request closed without merging**
