### PR TITLE
Create ssh.yml

### PR DESCRIPTION
**Pull request by Exochos**
This is an action to test that the runner can login to the instance and has sudo powers
As well as being able to get the deployed secrets.

### CODE REVIEW

**Review by brinkbrink — APPROVED** [review]
Testing testing 1 2 3

**Comment by taylorpapke** [comment]
@Exochos Does this need to be merged in order to test?

**Comment by Exochos** [comment]
> @Exochos Does this need to be merged in order to test?

Yeah it does, I can test on my local machine but I can't add github actions to this repo unless I edit one that is currently there

**Review by taylorpapke — APPROVED** [review]

**Comment by theGaryLarson** [comment]
can you rollback and see if the issue persists? Also, I was paranoid but I created a fork in the early stages and would run the github actions there I don't know how feasible that is now with deployment setup and the progress that has been made.

**Pull request merged**
