### PR TITLE
NSCEvents_NestJs_Sprint_5_Unit_Testing

### PR DESCRIPTION
**Pull request by MuhammadNSC**
Checking current testing and adding more tests

### CODE REVIEW

**Comment by brinkbrink** [comment]
Screenshot 2024-04-18 at 5 44 05 PM

Hi @MuhammadNSC ! I know this is a draft but wanted to point out the failing CodeFactor tests. If you click the "Details" link you can go through and fix them pretty easily. Thanks!

**Review by taylorpapke — APPROVED** [review]
Looks good to me:
Screenshot 2024-04-23 at 1 42 54 AM

**Review by heosman — APPROVED** [review]
All the tests for the auth controller passed.

Screenshot 2024-05-01 030013

**Comment by MaddasaHatter** [comment]
I am still showing that there are some checks that this PR isn't passing successfully for the code factor but all the tests for the auth controller passed.

**Pull request merged**
