### PR TITLE
nsc-events-nestjs_7_114_enable-nestjs-auto-assign-issues

### LINKED ISSUE #114: Chore: Enable NestJS Auto-Assign Issues Workflow
This issue is for implementing a .github/workflows yaml file that will auto-assign an issue to whomever creates the issue.

GitHub Marketplace action: https://github.com/marketplace/actions/auto-assign-issue

Documentation used: https://andrewlock.net/auto-assigning-issues-using-a-github-action/

Steps:
- Created personal access token for seattlecolleges and added to organization secrets.
- Created yaml file in .github/workflows folder that utilizes the secret to auto-self-assign creator of the issue.

### PR DESCRIPTION
**Pull request by taylorpapke**
Resolves #114 

Once merged, this should auto-assign developers to the issues they create for this repo.

### CODE REVIEW

**Review by Seiyaroo — APPROVED** [review]
Neat feature if / when it works. LGTM

**Review by heosman — APPROVED** [review]
LGTM!

**Comment by MuhammadNSC** [comment]
Just as added to the belinda project this feature will also work well with NSC events. Looks good

**Review by Ali-7s — APPROVED** [review]
LGTM

**Pull request merged**
