### PR TITLE
nsc-events-nestjs_4_53_auth-controller-unit-test

### LINKED ISSUE #53: Unit tests for Auth controller and services module (backend): auth controller unit test
Currently, there’s no test cases for the methods in the auth controller module, so I would like to create a unit test for that module and test each method inside of that module.

### PR DESCRIPTION
**Pull request by TroyFPV48**
resolves #53

### CODE REVIEW

**Comment by brinkbrink** [comment]
Please following the "Details" links to the checks that are failing here. There's some stuff that needs fixing here. @TroyFPV48

**Review by TroyFPV48 — COMMENTED** [review]
Reviewed

**Review by TroyFPV48 — COMMENTED** [review]
Test review

**Comment by TroyFPV48** [comment]
Screen Shot 2023-12-05 at 4 01 14 PM
auth controller test passed

**Review by bcko — APPROVED** [review]

**Review by taylorpapke — APPROVED** [review]
Nice work!
Screenshot 2023-12-05 at 10 44 17 PM

**Pull request merged**
