### PR TITLE
nsc-events-nestjs_4_60_auth-service-unit-test

### LINKED ISSUE #60: Unit tests for Auth controller and services module (backend): auth services unit test
Currently, there’s no test cases for the methods in the auth services module, so I would like to create a unit test for that module and test each method inside of that module.

### PR DESCRIPTION
**Pull request by TroyFPV48**
resolves #60

### CODE REVIEW

**Review by brinkbrink — CHANGES_REQUESTED** [review]
Hi @TroyFPV48 please check out the "Details" link next to CodeFactor and fix the errors it is bringing up:

Screen Shot 2023-12-06 at 9 51 19 AM

Thank you!

**Comment by taylorpapke** [comment]
@brinkbrink I had closed the issue that this was associated with prematurely as it was broken into 2 PR's - 1 for auth service and 1 for auth controller. This one pertains to auth service. @TroyFPV48, please create a fresh branch from main and open another PR for this. This is not a bad thing as this was a hard PR to fix.

**Comment by TroyFPV48** [comment]
ok

**Comment by TroyFPV48** [comment]
new PR created: https://github.com/SeattleColleges/nsc-events-nestjs/pull/62

**Pull request closed without merging**
