### PR TITLE
nsc-events_3_39_update-user-dto-refactor

### LINKED ISSUE #39: Refactor: Add DTO to update a User
As a developer, I want to have the User Entity to have a Data Transfer Object (DTO) for updating a user.
As a developer, I want my code to be cohesive and coding conventions and styles to match across both NSC Events and [Belinda's Closet](https://github.com/SeattleColleges/belindas-closet-nestjs), our twin project.

Currently we have a DTO for signing up a new user in the Auth module. This makes adding a user here redundant, we can remove these methods from the controller and the service.
We want a DTO for updating the user and to refactor the controller to utilize this.
We want the service to utilize the model's findByIdAndUpdate method for the updateUser method.

This mimics the work done issue [#50](https://github.com/SeattleColleges/belindas-closet-nestjs/issues/50) for Belinda's Closet.

This relates to issue #38 Unit testing, I would like to refactor the service and controller before finishing testing.

### PR DESCRIPTION
**Pull request by CourtneyHoppus**
Resolves #39 

I added a DTO for updating the user and refactored the controller and service to utilize this.
I removed the unused imports and the non-typed request parameters.
Removed redundant add User methods, the Auth module handles this.

When running `npm install` to be able to run the app with it's dependencies, it found a critical vulnerability:

Screenshot 2023-11-15 at 10 56 22 AM

-------------

Screenshot 2023-11-15 at 10 56 43 AM

I resolved this by running `npm audit fix`

[Here](https://nextjsdeployment.notion.site/Connection-f810cd7541064cdeab6b731a5da32893) is a document about connecting to a MongoDB Compass (local) instance. This is also the basic setup to connect to an Atlas (cloud) instance.

To test:
- pull branch
- run `npm install`
- run locally
- you must have a valid mongodb connection string and .env file set up
- run tests on user in Postman
- you must either
   - have a previously created user in your database and login through the `/auth/login` route
   OR:
   - create a new user using the `/auth/signup` route
- using the token sent back when logging in or creating a user as your bearer token to test:
  - get all users at `/users` route with GET call
  - get user by id at `/users/find/:id` route with GET call
  - get user by email at `/users/email/:email` route with GET call
  - update a user at `/users/update/:id` route with PATCH call
  - delete a user at `/users/remove/:id` route with DELETE call

### CODE REVIEW

**Comment by brinkbrink** [comment]
@CourtneyHoppus Some checks are failing here. I also auto-updated your branch. The checks were failing before the update, too, FYI. Click the "details" link next to the failed check for more details. Some of them can be automatically fixed but I didn't go through and do that in case you wanted to check them out.

**Review by brinkbrink — CHANGES_REQUESTED** [review]
@CourtneyHoppus Some checks are failing here. I also auto-updated your branch. The checks were failing before the update, too, FYI. Click the "details" link next to the failed check for more details. Some of them can be automatically fixed but I didn't go through and do that in case you wanted to check them out.

**Comment by CourtneyHoppus** [comment]
Thanks @brinkbrink. When referring to the automatic fix, is there a linter we are using that I can run on my branch or is it the third-party CodeFactor that wants permission to access GitHub?

**Review by Robel-003 — CHANGES_REQUESTED** [review]
This looks great, nice job! All the api routes work as expected once I have signed up and signed in and used the provided token. 
The update route returns helpful messages when updating a user. The delete api route doesn't seem to work though "/users/delete/:id", but this route works "/users/remove/:id"

Also, in the 4th bullet point under To test, I think it'd be helpful to add the [connection link documentation](https://nextjsdeployment.notion.site/Connection-f810cd7541064cdeab6b731a5da32893) Tin created.

**Comment by tinpham5614** [comment]
All endpoints are functional. It would be helpful to have a success or failure message when removing a user.

**Comment by CourtneyHoppus** [comment]
@Robel-003 I added that link and updated the testing directions.
@brinkbrink I corrected the issues that were causing the checks to fail.

**Review by Robel-003 — APPROVED** [review]
Looks great and it's working perfectly, thank you for making those changes!

**Pull request merged**
