### PR TITLE
nsc-events-nestjs_6_108_getAllActivites_numEvents

### PR DESCRIPTION
**Pull request by cshimm**
Adds optional parameter numEvents to get all activities endpoint '/api/events?numEvents=x'. if no numEvents query parameter is supplied, '/api/events' will return 5 events. This will help facilitate pagination on the home page without returning all events every time the '/api/events' endpoint is hit.

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Works for me. Ran the backend and then tested http requests with postman. Can't really tell from my output but the following postman requests retrieved the correct amount of events in each case:
2 events:
Screenshot 2024-04-30 at 1 02 25 AM
default (5 events):
Screenshot 2024-04-30 at 1 02 06 AM
6 events:
Screenshot 2024-04-30 at 1 01 48 AM

**Comment by tinpham5614** [comment]
Everything looks good to me.
There is an error I get:
image

After removing type annotation:
image

**Comment by cshimm** [comment]
I talked with @bcko about this yesterday, he recommended I change the endpoint to follow API conventions by adding a query parameter rather than just passing in the number as an endpoint:
 '/api/events?numEvents=x'
instead of 
'/api/events/x'

The newest commit reflects this change!

**Review by bcko — APPROVED** [review]
Great job!

**Comment by IsaacJrTypes** [comment]
I was able to get the default behavior to return 5 events, but got a 404 when I request a specific number of events. 
Default:
CleanShot 2024-05-01 at 16 23 56@2x

CleanShot 2024-05-01 at 16 24 48@2x

**Comment by cshimm** [comment]
@IsaacJrTypes Yes that is because I modified the endpoint to now have a query parameter. Try testing this way:
image

**Review by IsaacJrTypes — APPROVED** [review]
Good to go :) 
CleanShot 2024-05-01 at 17 36 55@2x

**Pull request merged**
