### PR TITLE
refactored user into userAuthSchema

### PR DESCRIPTION
**Pull request by Exochos**
refactored /src/auth/user.schema to /r/auth/UserAuthSchema

tested the signup route and the login route to make sure both are working correctly 
test1

test2

everything seems to be working fine.

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
LGTM

**Comment by taylorpapke** [comment]
@Seiyaroo @theGaryLarson Should we go ahead and bypass signed commits for now to get this merged in?

**Comment by theGaryLarson** [comment]
@taylorpapke yes that was the decision during our meeting. Just squash and merge if we have the approvals and checks pass. Please make note of the person/people who hasn't setup signed commits yet. Please create a thread in mag 7 and include their name or gh handle.

**Comment by taylorpapke** [comment]
@theGaryLarson Should we hold off on deleting branches after merge since they may be required for grading? If so, how will we know when it is ok to finally delete the branches. Just a thought I had.

**Comment by Seiyaroo** [comment]
> @theGaryLarson Should we hold off on deleting branches after merge since they may be required for grading? If so, how will we know when it is ok to finally delete the branches. Just a thought I had.

Thats a good question. @bcko what's your opinion on that?

**Comment by theGaryLarson** [comment]
@taylorpapke @Seiyaroo @bcko Deleting them should be fine. That is what we have setup as the standard. If needed @bcko can restore them. Unless he wants to change it up.

**Comment by bcko** [comment]
@taylorpapke @Seiyaroo @theGaryLarson 
Thank you for checking. Since I will be reviewing both pull requests and branches, it's perfectly fine to delete any branches that have already been merged.

**Pull request merged**
