### PR TITLE
nsc-events-nextjs _ 4 _ 95 _ change-password-Page

### LINKED ISSUE #95: Change Password Page Functionality: Change password
As a developer, I want to have a change password functionality to support the front-end change password page.
Link to USER STORY: https://github.com/SeattleColleges/nsc-events-nextjs/issues/242

### PR DESCRIPTION
**Pull request by TuongPhamM**
resolves #95 
Working without package-lock.json file change.

https://github.com/SeattleColleges/nsc-events-nestjs/assets/77989401/ebb12ecf-910d-40ed-a361-c1e2f1393495

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Worked for me! I was able to change password in Postman while using bearer token from a logged in user. I was then able to log in with the new password.

**Review by heosman — APPROVED** [review]
I was able to change my password on Postman using my bearer token and sign in with the new password.

image

**Comment by heosman** [comment]
@TuongPhamM Please address the CodeFactor issues so that your PR can be merged.

**Comment by TuongPhamM** [comment]
> @TuongPhamM Please address the CodeFactor issues so that your PR can be merged.

Okay, it should have passed all the checks by now.

**Pull request merged**
